# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: drzel's Umbrella
email: sheldon.johnson@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal blog of Sheldon J. Johnson. I'll post things
  as I learn them.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://drzel.github.io" # the base hostname & protocol for your site
github_username:  drzel

# Build settings
markdown: kramdown
